version: "3.8"

services:
  webizly:
    image: kaw393939/webizly:production
    container_name: grace-burke-production
    pull_policy: always
    restart: always
    networks:
       - traefik
       - backend
    ports:
      - "8080"
    environment:
      - DEPLOYMENT=production
      - DATABASE_URL=postgresql+psycopg2://production:production@postgres:5432/production
    logging:
      driver: gelf
      options:
        gelf-address: "udp://localhost:12201"
        tag: "production"
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.grace-burke.rule=Host(`www.grace-burke.com`) || Host(`grace-burke.com`)
      - traefik.http.routers.grace-burke.entrypoints=https
      - traefik.http.routers.grace-burke.tls=true
      - traefik.http.routers.grace-burke.tls.certresolver=simple-resolver
      - traefik.http.services.grace-burke.loadbalancer.server.port=8080
networks:
  traefik:
      name: traefik
      external: true
  backend:
      name: backend
      external: true
